# -*- coding: utf-8 -*-
"""real_final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syJDwbsIMUexo9UVSzaH7GCfQEba8tXi

# 환경 설정
"""

!pip install ultralytics
!pip install opencv-python pillow matplotlib

"""## 파일 다운로드"""

import gdown
import zipfile
import os

# https://drive.google.com/file/d/10VZf9IqZ0bVHFCIcELrWmLS01Kh0pzF-/view?usp=drive_link
file_id = "10VZf9IqZ0bVHFCIcELrWmLS01Kh0pzF-"
zip_name = "dataset.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", zip_name, quiet=False)

dir = "dataset"
with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall(dir)

os.listdir(dir)

with open("dataset/data.yaml", "r", encoding="utf-8") as f:
    print(f.read())

data_yaml = "dataset/data.yaml"

with open(data_yaml, "r") as file:
    lines = file.readlines()

lines[0] = "train: /content/dataset/train/images\n"
lines[1] = "val: /content/dataset/valid/images\n"
lines[2] = "test: /content/dataset/test/images\n"

with open(data_yaml, "w") as file:
    file.writelines(lines)

"""# train"""

from ultralytics import YOLO
model_yolos=YOLO("yolov8s.pt")

model_yolos.train(data=data_yaml, epochs=50, batch=16, patience=0, lr0=0.001, mosaic=True, mixup=True, degrees=10, scale=0.5, shear=10, flipud=0.5, fliplr=0.5)

from ultralytics import YOLO
model__ = YOLO("/content/runs/detect/train__/weights/best.pt")   # __ 채우기

from google.colab import files
files.download('/content/runs/detect/train__/weights/best.pt')  # __ 채우기

"""# Test"""

result=model__.predict('/content/__.jpg')   # __ 채우기
result[0].show()